export default {
  index: "Welcome",
  Ads: { display: "hidden" },
  Channels: { display: "hidden" },
  Classes: { display: "hidden" },
  Commands: { display: "hidden" },
  Copyrights: { display: "hidden" },
  Currency: { display: "hidden" },
  Guides: "Guides",
  Infractions: { display: "hidden" },
  ItemTiers: { display: "hidden" },
  Licensing: { display: "hidden" },
  Parties: { display: "hidden" },
  Profiles: { display: "hidden" },
  Ranks: { display: "hidden" },
  ResourcePacks: { display: "hidden" },
  SimpleVoiceChat: { display: "hidden" },
  Voting: { display: "hidden" },
  World: { display: "hidden" },
  WorldTime: { display: "hidden" },
  "*": {
    theme: {
      footer: false,
      breadcrumb: false,
      typesetting: "article",
      pagination: false,
    },
  },
  contact: {
    title: "Forum",
    type: "page",
    href: "https://arknesia.com",
  },
};
